inherit_from: .rubocop-todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - Gemfile
    - gemfile_arranger.gemspec
    - bin/**
    - lib/**/*.rake
  Exclude:
    - pkg/**
StringLiterals:
  EnforcedStyle: single_quotes
